
package maven.projetoCD.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.13
 * Thu Jan 14 11:38:43 GMT 2021
 * Generated source version: 2.6.13
 */

@XmlRootElement(name = "startTimeResponse", namespace = "http://projetoCD.maven/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "startTimeResponse", namespace = "http://projetoCD.maven/")

public class StartTimeResponse {

    @XmlElement(name = "return")
    private long _return;

    public long getReturn() {
        return this._return;
    }

    public void setReturn(long new_return)  {
        this._return = new_return;
    }

}

