
package maven.projetoCD.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.13
 * Sun Jan 03 13:56:13 GMT 2021
 * Generated source version: 2.6.13
 */

@XmlRootElement(name = "bananas", namespace = "http://projetoCD.maven/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bananas", namespace = "http://projetoCD.maven/")

public class Bananas {


}

